    <footer>
        <h2><i>CSC 174:</i> Project 3</h2>
        <a class="tzine" href="http://www.jqueryscript.net/gallery/jQuery-Portfolio-Plugin-with-Thumbnail-Growing-Effect.html">Pluggins Found: <i><b>Here</b></i></a>
    </footer>

     <!-- JavaScript includes - jQuery and our own script.js -->
	<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
	<script src="assets/js/script.js"></script>

<!-- Other site information collected here:
Kaplan Ed foundation: http://www.kaplanedfoundation.org/the-program/meet-the-kaplan-scholars/chadrick-frederick/

Borough Manhattan Community College: http://www.bmcc.cuny.edu/news/news.jsp?id=11352

CSS and froms from prior labs and projects were used and customized to enhance layout for project 3.

 -->